version: '3.1'

services:
  copens:
    restart: always
    build: . 
    depends_on:
      - copens_db
    command: >
      bash -c "python manage.py collectstatic --noinput
      && uwsgi --uid root --master --http 0.0.0.0:8000 --module copens.wsgi --static-map /static_cwm=static_all --process 4 --manage-script-name --mount=/copens=copens/wsgi.py"
    ports:
      - '8000:8000'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
  copens_db:
    restart: always
    image: library/mariadb 
    environment:
      - MYSQL_ROOT_PASSWORD=copens
      - MYSQL_DATABASE=copens
      - MYSQL_USER=copens
      - MYSQL_PASSWORD=copens
    volumes:
      - ./mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
  copens_engine:
    restart: always
    build: ./copens-engine
    volumes:
      - /usr/local/share/cwb/registry:/usr/local/share/cwb/registry 
      - /var/local/LOPEN/corpus/CWB/data:/var/local/LOPEN/corpus/CWB/data
    logging:
      options:
        max-size: '10m'
        max-file: '3'
      driver: json-file
